---
- hosts: all

  tasks:
    - name: deploy dotfiles
      file: src="~/.dotfiles/files/{{ item }}" dest="~/.{{ item }}" state=link
      with_items:
        - vimrc
        - aliases
        - gitconfig
        - gitignore
        - gitmessage
        - zshrc
        - zshenv
        - latexmkrc

    - name: Setup user dotfile dirs folder
      file: path="~/{{ item }}" state=directory
      with_items:
        - ".zsh"
        - "bin"

    - name: Pull down git completion
      get_url: url="https://raw.githubusercontent.com/git/git/master/contrib/completion/{{ item }}" dest="~/.zsh/_git"
      with_items:
        - git-completion.zsh

    - name: Pull down git completion
      get_url: url="https://raw.githubusercontent.com/git/git/master/contrib/completion/{{ item }}" dest="~/{{ item }}"
      with_items:
        - git-completion.bash
        - git-prompt.sh

    - name: hub zsh completion
      get_url: url="https://raw.githubusercontent.com/github/hub/master/etc/hub.zsh_completion" dest="~/.zsh/_hub"

    - name: Setup Sublime Text 3 link
      file: src="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" dest="~/bin/subl" state=link force=yes
